name: Deployment Workflow

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Develop
      url: https://google.com

    steps:
      - name: Install dependencies
        run: echo 'Deployed'

