name: Deployment Workflow

on:
  deployment:
    types:
      - created
      - updated
      - deleted

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: echo 'Deployed'

